name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DIR_WEBAPP: ./SiteContagem
  IMAGEM_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/sitecontagemcampus
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build de imagem
      run: |
        cd ${{ env.DIR_WEBAPP }}
        docker build . --file Dockerfile --tag ${{ env.IMAGEM_DOCKERHUB }}:latest
      
